name: build-cmake-linux
on: [push]
jobs:
  build-using-cmake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.8.1%2Bcpu.zip && unzip libtorch-cxx11-abi-shared-with-deps-1.8.1+cpu.zip && rm libtorch-cxx11-abi-shared-with-deps-1.8.1+cpu.zip && ls -l
