name: build-cmake-macos
on:
  push:
    branches:
      - master
      - develop
    paths:
      - libtorch-examples/**
  pull_request:
    branches:
      - master
      - develop
    paths:
      - libtorch-examples/**
jobs:
  build-using-cmake-on-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: sh build-macos.sh
