name: build-cmake-linux
on: [push]
jobs:
  build-using-cmake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir build && cd build && cmake -DINSTALL_TORCH=true -DCUDA=false -DINSTALL_PYTHON_DEPENDENCIES=false -DDOWNLOAD_MNIST=false ../ && make
